### ISSUE TITLE
Configuração da estrutura inicial do projeto

### ISSUE THREAD

**Issue by waldrey** [coberturaimoveis/backend#7]
# 🔨 Objetivo

Issue criada para definir padrão estrutural da aplicação para facilitar o entendimento de toda equipe @coberturaimoveis/backenders. Será necessário a aprovação de todos membros da equipe para ser *mergeada* para master assim podemos criar branch das features da api para atender o frontend do projeto.

## Todolist

- [x] Configuração do Typescript;
- [x] Configuração base do bootstrap da aplicação;
- [x] Configuração do mongo/mongoose
- [x] Definido uma estrutura para criação de rotas
- [x] Definido uma estrutura para criação de schemas do mongo
- [x] Definido uma estrutura para criação de controllers

### Informações básicas
* **Branch:**
    * structure-folders

**Comment by waldrey** [comment]
Algumas configurações foram adicionadas no commit https://github.com/coberturaimoveis/backend/commit/c2574b1, favor validarem para conclusão de alguns itens da todolist.

**Comment by GuilhermeSillva** [comment]
Ia comentar sobre a estrutura das funções public/private, mas ta td ok, so vou conseguir testar na segunda, mas aparentemente está certinho

**Comment by waldrey** [comment]
✅ **Issue** foi atendida completamente no commit https://github.com/coberturaimoveis/backend/commit/8a5165e4b9c092b08c0795cd5da1a3dc8d6fe933
